### ISSUE TITLE
Failed to convert/import solution due to missing asset.

### ISSUE THREAD

**Issue by kellymor** [microsoft/WinObjC-Samples#14]
I was unable to build the Toast Notifications sample in VS 2015 due to an import issue:

Download sample from https://github.com/Microsoft/WinObjC-samples/tree/develop
Open command prompt
Change directory to [Sample Root Folder]\Scenarios\Toast Notifications\ToastNotificationSample
Run VSImporter, Note error message about missing asset
Open solution in VS 2015

Expected Result:
Project loads successfully

Actual Result:
Project fails to load.  Reloading project results in error message below.

---------------------------
Microsoft Visual Studio
---------------------------
The item metadata "%(FullPath)" cannot be applied to the path "Assets\Square44x44Logo.targetsize-24_altform-unplated.png". C:\Users\kellymor.REDMOND\Documents\Visual Studio 2015\Projects\WinObjCSamples\Scenarios\Toast Notifications\ToastNotificationSample\ToastNotificationsSample.vsimporter\ToastNotificationsSample-WinStore10\Assets\Square44x44Logo.targetsize-24_altform-unplated.png
---------------------------
OK   
---------------------------

**Comment by antoine-haas** [comment]
Hey @kellymor,

I was unable to repro this using the release sdk: importing, building & running the sample both from the develop and master branches worked fine. What version of the SDK did you use?

**Comment by kellymor** [comment]
Using the latest from develop.

**Comment by antoine-haas** [comment]
This error, as well as vs importer warning "[W] Failed to open C:\MyAppPath\MyApp.vsimporter\MyApp-WinStore10\Assets\Square44x44Logo.targetsize-24_altform-unplated.png for writing." are because the path of your app is too long for Windows to properly handle. To fix this, simply move your app project folder to a shorter location and re-import your project with vsimporter. This issue is now covered in the [FAQ](https://github.com/Microsoft/WinObjC/wiki/FAQ#im-getting-error-the-item-metadata-fullpath-cannot-be-applied-to-the-path-assetssquare44x44logotargetsize-24_altform-unplatedpng-when-trying-to-load-my-project-in-visual-studio-and-warning-w-failed-to-open-cmyapppathmyappvsimportermyapp-winstore10assetssquare44x44logotargetsize-24_altform-unplatedpng-for-writing-in-vsimporter-what-should-i-do).
